version: '2'
services:
    jhipsterstartupapplication-app:
        image: jhipsterstartupapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhipsterstartupapplication-oracle:1521:jhipsterStartupApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
